# PROJECT_NAME defaults to name of the current directory.
# in the project name dont set '-'
# https://github.com/docker/libnetwork/issues/929#issuecomment-184129857
# should not to be changed if you follow GitOps operating procedures.
PROJECT_NAME = $(notdir $(PWD))

THIS_FILE := $(lastword $(MAKEFILE_LIST))
CMD_ARGUMENTS ?= $(cmd)

# Retrieve the Makefile used to manage the Docker environment
COMPOSE_FILE	:= docker-compose.yml
# export such that its passed to shell functions for Docker to pick up.
export PROJECT_NAME

# all our targets are phony (no files to check).
.PHONY: shell help build rebuild service login test clean prune


rebuild:
	# force a rebuild by passing --no-cache
	docker-compose build --no-cache

build:
	# only build the container. Note, docker does this also if you apply other targets.
	docker-compose stop
	docker-compose build


prune:
	# clean all that is not actively used
	docker-compose stop
	docker system prune -af

logs: ## Follow logs generated by all containers
	docker-compose logs -f --tail=0

logs-full: ## Follow logs generated by all containers from the containers creation
	docker-compose logs -f

stats: ## Print real-time statistics about containers resources usage
	docker stats $(docker ps --format={{.Names}})


ps: ## List all containers managed by the environment
	docker-compose ps

php: ## Open a terminal in the "php-fpm" container
	docker-compose exec  php-fpm sh


nginx: ## Open a terminal in the "nginx" container
	docker-compose exec nginx sh

hosts: ## create value in the hosts
	sh bin/host.sh

start: ## Start the environment
	docker-compose stop
	docker-compose up -d --remove-orphans

stop: ## Stop the environment
	docker-compose stop

destroy: ## destroy the environment
	docker-compose stop
	@docker-compose -p $(PROJECT_NAME) down --remove-orphans -v --rmi all 2>/dev/null \
	&& echo 'environment "$(PROJECT_NAME)" removed.'
	docker rmi -f phpmyadmin/phpmyadmin
	docker rmi -f nginx:latest
	docker rmi -f php:7.3-fpm
	docker rmi -f mariadb:latest


.DEFAULT_GOAL := help
help:
	@grep -E '(^[a-zA-Z_-]+:.*?##.*$$)|(^##)' $(MAKEFILE_LIST) \
		| sed -e 's/^.*Makefile://g' \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "\033[32m%-30s\033[0m %s\n", $$1, $$2}' \
		| sed -e 's/\[32m##/[33m/'